//
// Created by Kos Ovechko on 12.10.22.
//

#ifndef CHIMNEY_EXHAUST_SMOKE_CONTROLLER_TIME_MODULE_H
#define CHIMNEY_EXHAUST_SMOKE_CONTROLLER_TIME_MODULE_H

uint32_t SECOND = 1000;
uint32_t MINUTE = 60 * SECOND;
uint32_t TEN_MINUTES = 10 * MINUTE;

uint32_t HOUR = 60 * MINUTE;

#endif //CHIMNEY_EXHAUST_SMOKE_CONTROLLER_TIME_MODULE_H
